### ISSUE TITLE
Max MQTT payload limit

### ISSUE THREAD

**Issue by MPM1107** [puuu/MQTT433gateway#37]
It seems like the compiled binaries use the default PubSubClient payload limit of 128 bytes, which is insufficient for sending RAW codes for some of my remotes. It would probably make sense to increase this limit.

**Comment by puuu** [comment]
128 bytes long raw message sounds very long. Did you have an example?
Can you try to dense the length of the raw message, by merging pules types?

**Comment by MPM1107** [comment]
Indeed, it surprised me as well. Sadly, there are only 2 pulse lengths for the main body of the packet, and 1 pulse length for the starting header, so no way of compacting it down.
It's a weird Italian-made window blind control system that doesn't follow any other protocol, they made up their own. The system supports up to 8 channels and when you press a button, the state of all 8 channels gets sent instead of only the one you changed, so that's where the huge packet comes from. I can post an example but I doubt it would help.
I tried compiling my own code with the message limit increased, but even though the compile was successful, the ESP was stuck in a boot loop after flashing it. Tried it a few times with different settings but gave up in the end.
The whole packet is exactly 128 bits long, so after all the other info that you have to include in the mqtt payload like the pulse lengths the 128 byte limit is just barely not enough.

**Comment by puuu** [comment]
Thank you for reporting this issue, commit 802b2adb1136d2ad5dc7b4d9295db6192aef32d9 increases the MQTT_MAX_PACKET_SIZE to 256.
