### ISSUE TITLE
RC switch to MQTT

### ISSUE THREAD

**Issue by denxhun** [puuu/MQTT433gateway#38]
Hi,

First of all this is a great project, I really like it.
May I miss something or the program intentionally not forwarding decoded switch messages to MQTT?
For example I see the following on the logs:
```
rf signal received: {"id":89,"temperature":21.61,"humidity":49.00,"battery":1,"channel":1} protocol= tfa status=0 repeats=1 deviceID=89
rf signal received: {"id":89,"temperature":21.61,"humidity":49.00,"battery":1,"channel":1} with protocol tfa deviceID=89
Publish MQTT message: rf434/recv/tfa/89 retain=1 .. {"id":89,"temperature":21.61,"humidity":49.00,"battery":1,"channel":1}
rf signal received: {"id":6,"unit":5,"state":"off"} protocol= conrad_rsl_switch status=0 repeats=1 deviceID=6
rf signal received: {"id":198,"temperature":16.16,"humidity":48.00,"battery":1,"channel":3} protocol= tfa status=0 repeats=1 deviceID=198
```

Is it possible to forward the Conrad switch messages to the MQTT - to let the homeassistant process it?

Thanks,
Denes

**Comment by puuu** [comment]
All received, recognised (=able to decode by an enabled RF protocol) and proved signals are forwarded as MQTT message.

All your shown messages have `status=0` [which mean it is the first received signal](https://github.com/puuu/ESPiLight/blob/master/src/ESPiLight.h#L33). To be proven, a message must received twice (Usually, all rf sender will send the same rf message more then three times). I expect, either your signal is to weak, or the protocol is unknown and you see by noise manipulated signals.
