### ISSUE TITLE
Build failed on Windows

### ISSUE THREAD

**Issue by denxhun** [puuu/MQTT433gateway#39]
Hi,

Congratulation, this is a really cool project I like it.
Unfortunately I'm unable to build it from source on Win 10 Atom.io + Platformio (latest, fresh installation both).
I'm sure a few small steps are missing from the build instructions but at the moment I have to depend on released binaries.

Thanks,
Denes

Build log attached: [build.log](https://github.com/puuu/MQTT433gateway/files/2414324/build.log)

**Comment by jimloki** [comment]
Same problem here. Can someone please help?

**Comment by denxhun** [comment]
I found a solution. A diff and a new file attached.
[platform.ini.txt](https://github.com/puuu/MQTT433gateway/files/2539963/platform.ini.txt)
[fw_version.py.txt](https://github.com/puuu/MQTT433gateway/files/2539967/fw_version.py.txt)

I hope I was a help.

**Comment by puuu** [comment]
Thank you for reporting. Indeed, the `build_flags` method used in `platformio.ini` is not windows compatible:
https://docs.platformio.org/en/latest/projectconf/section_env_build.html#dynamic-build-flags

@denxhun: Thank you for your hint. Please feel free to submit a pull request. (Please check the style and header of other python scripts of this project.)

**Comment by puuu** [comment]
Pull request #41 is merged. Should solve this issue.
