### ISSUE TITLE
Prebuild scripts borked

### ISSUE THREAD

**Issue by drzacek** [puuu/MQTT433gateway#47]
Hi. 
Just so you know that your prebuild scripts (I don't know what they doing, just get the exact version string?)
are purely based on git repo and don't work when someone just downloads zipped dir (as many people often do, since this is an option).

Not only the scripts not work, it prohibits the whole project to build. Maybe put them as optional, or maybe that they end gracefully when they don't find git repo.

**Comment by puuu** [comment]
Thank you for reporting this issue. Should be fixed in 675a2e96d43f299d6957577dcb24e97943d78abb .
